---
- hosts: acg
  tasks:
  - name: change url
    become: yes
    lineinfile:
      path: /etc/gitlab/gitlab.rb #/home/jason/Documents/GitHub/install-gitlab-on-server/ansible-files/test.txt 
      regexp: 'external_url'
      line: 'external_url kursgn.southcentralus.cloudapp.azure.com' #https://gitlab-prod.centralus.cloudapp.azure.com/admin'
      state: present
  - name: reconfigure gitlab ctl
    become: yes
    shell: gitlab-ctl reconfigure
  - name: update gitlab
    become: yes
    shell: | 
      apt udpate
      apt install gitlab-ee